routes/web.php
<?php

use App\Http\Controllers\Identifier\IndexController as IdentifierIndexController;
use App\Http\Controllers\Identifier\UpdateController as IdentifierUpdateController;
use App\Http\Controllers\Report\CreateController as ReportCreateController;
use App\Http\Controllers\Report\ShowController as ReportShowController;

use App\Http\Controllers\UtilController;

use CodeZero\LocalizedRoutes\Controller\FallbackController;
use CodeZero\LocalizedRoutes\Middleware\SetLocale;
use Illuminate\Support\Facades\Route;

Route::localized(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('home');

    /**
     * Identifier
     */
    Route::name('identifier.')->group(function () {
        Route::get(Lang::uri('report-ufo'), IdentifierIndexController::class)->name('index');
    });

    /**
     * Report
     */
    Route::name('report.')->group(function () {
        Route::get(Lang::uri('report'), ReportShowController::class)->whereNumber('id')->name('show');
    });
});

/**
 * Identifier
 */
Route::name('identifier.')->group(function () {
    Route::post('identifier/update', IdentifierUpdateController::class)->name('update');
});

/**
 * Util
 */
Route::name('util.')->group(function () {
    Route::get('util/languages/{country_iso}', [UtilController::class, 'languages'])->where('country_iso', '[a-z]{2}')->name('languages');
});

Route::fallback(FallbackController::class)->middleware(SetLocale::class);

app/Http/Controllers/Identifier/IndexController.php
<?php

namespace App\Http\Controllers\Identifier;

use App\Models\Country;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function __invoke(Request $request)
    {
        $countries = Country::with('languages')->get();

        return view('identifier/index', [
            'countries' => $countries,
        ]);
    }
}

app/Http/Controllers/Identifier/UpdateController.php
<?php

namespace App\Http\Controllers\Identifier;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UpdateController extends Controller
{
    public function __invoke(Request $request)
    {
        $q = 0;
        $response = [];

        if ($request->input('report')) {
            $request->session()->put('identifier_report', 1);
            $response['location'] = route('report.create');
        } else {
            $answers = [];

            foreach ($request->all() as $key => $value) {
                if (preg_match('/^q(\d+)$/', $key, $matches)) {
                    $answers[] = $key . $value;
                    $q = intval($matches[1]);
                }
            }

            sort($answers);
            $answers = implode(',', $answers);
            $request->session()->put('identifier_answers', $answers);

            $suggestions = [
                'q1b' => [ // afterwards
                    'backscatter',
                    'bird_insect',
                    'dirt',
                    'droplet',
                    'lens_flare',
                    'reflection',
                ],
                'q1a,q2a,q3a' => [ // live, moving consistently, illuminated
                    'aircraft',
                    'contrail',
                    'inspection_train',
                    'meteor',
                    'satellite',
                    'starlink',
                    'thai_lantern',
                ],
                'q1a,q2a,q3b' => [ // live, moving consistently, not illuminated
                    'contrail',
                    'foil_balloon',
                    'hot_air_balloon',
                    'plastic_bag',
                    'solar_balloon',
                    'unusual_aircraft',
                    'weather_balloon',
                ],
                'q1a,q2b,q3a' => [ // live, moving irregularly, illuminated
                    'drone',
                    'helicopter',
                    'promotional_lights',
                ],
                'q1a,q2b,q3b' => [ // live, moving irregularly, not illuminated
                    'foil_balloon',
                    'plastic_bag',
                ],
                'q1a,q2c,q3a' => [ // live, stationary, illuminated
                    'art_project',
                    'beacon_lights',
                    'helicopter',
                    'industrial_lights',
                    'inspection_train',
                    'lightning',
                    'planet',
                    'promotional_lights',
                    'star',
                ],
                'q1a,q2c,q3b' => [ // live, stationary, not illuminated
                    'helicopter',
                    'kite',
                    'praying_bird',
                    'smoke_ring',
                    'sundog',
                    'unusual_cloud',
                    'zeppelin',
                ],
            ];

            if (array_key_exists($answers, $suggestions)) {
                $identifications = Identification::whereIn('key', $suggestions[$answers])->get();
                $response['result_html'] = view('identifier.result', ['identifications' => $identifications])->render();
            }
        }

        if (array_key_exists('result_html', $response)) {
            $response['step'] = $q;
        } else {
            $response['step'] = $q + 1;
        }

        return response()->json($response);
    }
}

resources/views/identifier/index.blade.php
@extends('layouts.app')

@section('title', __('identifier.h1'))

@section('content')
    <div class="o-page">
        <div class="o-wrapper o-wrapper--narrow">
            @foreach ($countries as $country)
                <h2>{{ $country->iso }}</h2>
                <ul>
                    @foreach ($country->languages as $language)
                        <li>{{ $language->iso }}</li>
                    @endforeach
                </ul>
            @endforeach
            <form action="{{ route('identifier.update') }}" class="c-identifier js-identifier" data-identifier-current-step="1" method="post">
                @csrf
                <div class="c-section">
                    <h1 class="u-m-m">{{ __('identifier.h1') }}</h1>
                    <p class="u-m-xxl">
                        {{ __('identifier.intro') }}
                    </p>
                    <ul class="c-identifier__steps o-wrapper__bleed">
                        <li class="c-identifier__step js-identifierStep o-wrapper__bleed" data-identifier-step="1">
                            <p class="c-identifier__question">{{ __('identifier.q1_label') }}</p>
                            <div class="c-identifier__answers">
                                <div class="c-identifier__answer">
                                    <input class="c-identifier__answerInput js-identifierAnswerInput" data-identifier-step="1" id="q1a" name="q1" tabindex="0" type="radio" value="a">
                                    <label role="button" class="c-identifier__answerLabel" for="q1a" tabindex="-1"><span>{{ __('identifier.q1.a') }}</span></label>
                                </div>
                                <div class="c-identifier__answer">
                                    <input class="c-identifier__answerInput js-identifierAnswerInput" data-identifier-step="1" id="q1b" name="q1" tabindex="0" type="radio" value="b">
                                    <label role="button" class="c-identifier__answerLabel" for="q1b" tabindex="-1"><span>{{ __('identifier.q1.b') }}</span></label>
                                </div>
                            </div>
                        </li>
                        <li class="c-identifier__step js-identifierStep o-wrapper__bleed" data-identifier-step="2">
                            <p class="c-identifier__question">{{ __('identifier.q2_label') }}</p>
                            <div class="c-identifier__answers">
                                <div class="c-identifier__answer">
                                    <input class="c-identifier__answerInput js-identifierAnswerInput" data-identifier-step="2" id="q2a" name="q2" type="radio" value="a">
                                    <label class="c-identifier__answerLabel" for="q2a"><span>{{ __('identifier.q2.a') }}</span></label>
                                </div>
                                <div class="c-identifier__answer">
                                    <input class="c-identifier__answerInput js-identifierAnswerInput" data-identifier-step="2" id="q2b" name="q2" type="radio" value="b">
                                    <label class="c-identifier__answerLabel" for="q2b"><span>{{ __('identifier.q2.b') }}</span></label>
                                </div>
                                <div class="c-identifier__answer">
                                    <input class="c-identifier__answerInput js-identifierAnswerInput" data-identifier-step="2" id="q2c" name="q2" type="radio" value="c">
                                    <label class="c-identifier__answerLabel" for="q2c"><span>{{ __('identifier.q2.c') }}</span></label>
                                </div>
                            </div>
                        </li>
                        <li class="c-identifier__step js-identifierStep o-wrapper__bleed" data-identifier-step="3">
                            <p class="c-identifier__question">{{ __('identifier.q3_label') }}</p>
                            <div class="c-identifier__answers">
                                <div class="c-identifier__answer">
                                    <input class="c-identifier__answerInput js-identifierAnswerInput" data-identifier-step="3" id="q3a" name="q3" type="radio" value="a">
                                    <label class="c-identifier__answerLabel" for="q3a"><span>{{ __('identifier.q3.a') }}</span></label>
                                </div>
                                <div class="c-identifier__answer">
                                    <input class="c-identifier__answerInput js-identifierAnswerInput" data-identifier-step="3" id="q3b" name="q3" type="radio" value="b">
                                    <label class="c-identifier__answerLabel" for="q3b"><span>{{ __('identifier.q3.b') }}</span></label>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="c-identifier__result js-identifierResult"></div>
            </form>
        </div>
    </div>
@endsection